// <auto-generated />
namespace JobBoardMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedviewsforPrivacyandTermsofServiceforHomeControllerChangedFooterelements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedviewsforPrivacyandTermsofServiceforHomeControllerChangedFooterelements));
        
        string IMigrationMetadata.Id
        {
            get { return "201704290050068_Added views for Privacy and Terms of Service for Home Controller . Changed Footer elements."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
