// <auto-generated />
namespace JobBoardMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class redofixnamingconventiontomatchCompaniesCompanyNametoJobsCompanyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(redofixnamingconventiontomatchCompaniesCompanyNametoJobsCompanyName));
        
        string IMigrationMetadata.Id
        {
            get { return "201704190139515_re do fix naming convention to match Companies.CompanyName to Jobs.CompanyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
