// <auto-generated />
namespace JobBoardMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedNavigationLinksupdatedandcleanedSitecssexternalstylesheetupdatedFooter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedNavigationLinksupdatedandcleanedSitecssexternalstylesheetupdatedFooter));
        
        string IMigrationMetadata.Id
        {
            get { return "201704262014125_Changed Navigation Links, updated and cleaned Site.css external stylesheet, updated Footer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
